backend/urls.py
from django.urls import path
from . import views 
app_name = "backend"
urlpatterns = [
    path('',views.dashboard, name='dashboard'),
    
    path('exam-add/',views.exam_add, name='exam_add'),
    path('exam-list/',views.exam_list, name='exam_list'),
    path('exam-edit/<int:exam_id>/',views.exam_edit, name='exam_edit'),
    
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('logout/', views.logout_page, name='logout'),
    
    path('question-add/', views.QuestionAddView.as_view(), name='question_add'),
    path('question/<int:id>/', views.question, name='question'),
    
    path('exam-history/', views.exam_history, name='exam_history'),
    path('result-details/', views.results, name='results'),
    
    path('examinee-list/',views.examinee_list, name='examinee_list'),
    path('examinee-profile/<int:id>/',views.examinee_profile_page, name='examinee_profile_page'),
    path('examinee-profile-update/<int:id>/',views.examinee_profile_update, name='examinee_profile_update'),
    
    path('notification/', views.NotificationView.as_view(), name='notification'),
    
    
    
    
    
    
    
    
    
]

onlineExam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('contents.urls')),
    path('backend/', include('backend.urls')),
    
    
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register, login, otp_verify
app_name = "user"
urlpatterns = [
    path("register/",register,name="register"),
    path("login/",login,name="login"),
    path("otp/",otp_verify,name="otp"),
    
    
]

backend/models.py
from django.db import models

# Create your models here.

backend/forms.py
from django import forms
from contents.models import Exam, Question, Choice

from django import forms
from users.models import Examinee
from datetime import datetime


class ExamForm(forms.ModelForm):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'id': "start_date", 'type': 'date'})
    )
    start_time = forms.TimeField(
        widget=forms.TimeInput(attrs={'class': 'form-control', 'id': "start_time", 'type': 'time'})
    )
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'id': "end_date", 'type': 'date'})
    )
    end_time = forms.TimeField(
        widget=forms.TimeInput(attrs={'class': 'form-control', 'id': "end_time", 'type': 'time'})
    )

    class Meta:
        model = Exam
        fields = ['title', 'description', 'start_date', 'start_time', 'end_date', 'end_time']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'id': "name", 'placeholder': ''}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'id': "description", 'placeholder': ''}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].required = False
        
        if self.instance and self.instance.id:
            self.fields['start_date'].initial = self.instance.start_time.date()
            self.fields['start_time'].initial = self.instance.start_time.time()
            self.fields['end_date'].initial = self.instance.end_time.date()
            self.fields['end_time'].initial = self.instance.end_time.time()

    def clean(self):
        cleaned_data = super().clean()

        # Get the date and time inputs
        start_date = cleaned_data.get('start_date')
        start_time = cleaned_data.get('start_time')
        end_date = cleaned_data.get('end_date')
        end_time = cleaned_data.get('end_time')

        if start_date and start_time:
            # Concatenate start date and time
            cleaned_data['start_time'] = datetime.combine(start_date, start_time)
        if end_date and end_time:
            # Concatenate end date and time
            cleaned_data['end_time'] = datetime.combine(end_date, end_time)

        return cleaned_data
    
class MCQAddForm(forms.Form):
    CHOICES = [
        ('1', 'Option 1'),
        ('2', 'Option 2'),
        ('3', 'Option 3'),
        ('4', 'Option 4'),
    ]
    exam = forms.ModelChoiceField(
        queryset=Exam.objects.all(),
        widget=forms.HiddenInput(attrs={'id': "exam"})  
    )
    question = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': "question" , 'placeholder':"Enter Question "})
    )
    choice_1 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': "choice_1" , 'placeholder':"Enter Option 1"})
    )
    choice_2 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': "choice_2" , 'placeholder':"Enter Option 2"})
    )
    choice_3 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': "choice_3" , 'placeholder':"Enter Option 3"})
    )
    choice_4 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': "choice_4" , 'placeholder':"Enter Option 4"})
    )
    correct_answer = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-select', 'id': "correct_answer"}),
        choices=CHOICES,
    )

    def save(self):
        # Create the Question instance
        question_instance = Question.objects.create(
            exam=self.cleaned_data['exam'],
            text=self.cleaned_data['question']
        )

        # Prepare the choices
        choices_data = [
            {'text': self.cleaned_data['choice_1']},
            {'text': self.cleaned_data['choice_2']},
            {'text': self.cleaned_data['choice_3']},
            {'text': self.cleaned_data['choice_4']},
        ]

        correct_answer_index = int(self.cleaned_data['correct_answer']) - 1
        
        # Create Choice instances
        choice_instances = []
        for i, choice_data in enumerate(choices_data):
            choice_instances.append(
                Choice.objects.create(
                    question=question_instance,
                    text=choice_data['text'],
                    is_correct=(i == correct_answer_index)
                )
            )
        
        return question_instance, choice_instances


class ExamineeUpdateForm(forms.ModelForm):
    class Meta:
        model = Examinee
        fields = ['name', 'email', 'father_name', 'education_qualification', 'phone', 'image']

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'id':"name", 'placeholder': ''}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'id':"email",'placeholder': ''}),
            'father_name': forms.TextInput(attrs={'class':'form-control', 'id':"father_name",'placeholder': ''}),
            'education_qualification': forms.TextInput(attrs={'class':'form-control','id':"education_qualification", 'placeholder': ''}),
            'phone': forms.TextInput(attrs={'class':'form-control', 'id':'phone', 'placeholder': ''}),
            'image': forms.ClearableFileInput(attrs={'class':'form-control-file', 'id':"image", 'placeholder': 'Upload Profile Picture'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['father_name'].required = False
        self.fields['education_qualification'].required = False
        self.fields['image'].required = False

backend/views.py
from django import forms
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from django.contrib.auth import authenticate,login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.contrib import messages
from django.views import View
from .forms import ExamForm, ExamineeUpdateForm, MCQAddForm
from django.forms import formset_factory, modelformset_factory, inlineformset_factory
from contents.models import Exam, Choice, Notification, Question, ExamineeResponse
from users.models import Examinee
from django.views.generic import View
from django.db.models import Count

class LoginPageView(View):
    template_name = 'backend/login.html'
    
    def get(self, request):
        message = ''
        return render(request, self.template_name, context={'message': message})
        
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username, password)
        if username  and password:
            user = authenticate(
            username=username,
            password=password,
            )
            if user is not None:
                login(request, user)
                return redirect('backend:dashboard')
        
        return render(request, self.template_name, context={})

@login_required(login_url="login/")
def logout_page(request):
    logout(request)
    return redirect("backend:login")
    
@login_required(login_url="login/")
def dashboard(request):
    number_of_exam = Exam.objects.count()
    number_of_examinee = Examinee.objects.count()
    
    context = {
        'page_name': 'dashboard',
        'page_title': "Dashboard",
        'number_of_examinee':number_of_examinee,
        'number_of_exam' : number_of_exam
    }
    return render(request, "backend/dashboard.html", context)

@login_required(login_url="login/")
def exam_add(request):
    if request.method == "POST":
        form = ExamForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request ,"Exam Add Successfully")
            return redirect("backend:exam_add")
        else:
            messages.error(request ,"Error!! Exam Not Add")
    
    form = ExamForm()
    context = {
        'page_name': 'exam_add',
        'page_title': "Exam Add",
        'form':form
    }
    return render(request, "backend/exam-add.html", context)

@login_required(login_url="login/")
def exam_list(request):
    exams = Exam.objects.all()
    context = {
        'page_name': 'exam_list',
        'page_title': "Exam List",
        'exams' : exams
    }
    return render(request, "backend/exam-list.html", context)

@login_required(login_url="login/")
def exam_edit(request, exam_id):
    exam = Exam.objects.filter(id=exam_id).first()
    if exam is None:
        messages.error("Exam Not Found")
        return redirect("backend:exam_list")
    if request.method == "POST":
        form = ExamForm(request.POST, instance=exam)
        
        if form.is_valid():
            form.save()
            messages.success(request ,"Exam Update Successfully")
            return redirect("backend:exam_edit", exam_id=exam_id)
        else:
            messages.error(request ,"Error!! Exam Not Add")
    
    form = ExamForm(instance=exam)
    context = {
        'page_name': 'exam_edit',
        'page_title': "Exam Edit",
        'form':form
    }
    return render(request, "backend/exam-edit.html", context)

@method_decorator(login_required(login_url="login/"), name='dispatch')
class QuestionAddView(View):
    template_name = 'backend/question-add.html'
    context = {
        }
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_name"] = "question_add"
        context["page_title"] = "Question Add"
        return context
    def get(self, request, *args, **kwargs):
        exam_id = request.GET.get('exam_id')
        num_questions = int(request.GET.get('number_of_question', 10))
        exams = Exam.objects.all()

        if not exam_id:
            return render(request, self.template_name, {'exams': exams, 'error': 'No exam ID provided.'})

        exam = get_object_or_404(Exam, id=exam_id)

        MCQAddFormSet = formset_factory(MCQAddForm, extra=0)
        initial_data = [{'exam': exam} for _ in range(num_questions)]
        formset = MCQAddFormSet(initial=initial_data)

        self.context['exam']=exam
        self.context['exams']=exams
        self.context['formset']=formset
        self.context['num_questions']=num_questions
        
        
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        exams = Exam.objects.all()
        MCQAddFormSet = formset_factory(MCQAddForm, extra=0)
        formset = MCQAddFormSet(request.POST)

        if formset.is_valid():
            for form in formset:
                form.save()
                messages.success(request, "Question Add Successfully")
            return redirect("backend:question_add")
        else:
            messages.error(request,"Invalid formset")
            self.context['exams']=exams
            self.context['formset']=formset
            return render(request, self.template_name, self.context)

@login_required(login_url="login/")
def question(request, id):
    exam = Exam.objects.filter(id=id).first()
    if exam is not None:
        questions = Question.objects.filter(exam=exam)
        questions_with_choices = []
        
        for question in questions:
            choices = Choice.objects.filter(question=question)
            questions_with_choices.append({
                'question' : question,
                'choices' : choices
            })
        context = {
            'questions_with_choices':questions_with_choices, 
            "exam":exam,
            'page_name':"exam",
            'page_title':"Question"
            
            }
        return render(request,"backend/question.html",context)
    else:
        return redirect("content:exam")

@login_required(login_url="login/")
def exam_history(request):
    # Group by exam and calculate the correct/incorrect counts
    if request.method == "GET"  and 'examinee_id' in request.GET:
        examinee_id = request.GET['examinee_id']
        examinee = Examinee.objects.filter(id= examinee_id).first()
        responses = ExamineeResponse.objects.filter(examinee=examinee).select_related('question__exam', 'selected_choice')
        
    else:
        responses = ExamineeResponse.objects.all().select_related('question__exam', 'selected_choice')
        
    exams = {}
    for response in responses:
        examinee = response.examinee
        exam = response.question.exam
        
        examinee_id = examinee.id
        exam_id = exam.id
        if examinee_id not in exams:
            exams[examinee_id]={}
            if  exam_id not in exams[examinee_id]:
                exams[examinee_id][exam_id] = {
                    'examinee_name':examinee.name,
                    'exam_title': exam.title,
                    'total_questions': 0,
                    'correct_answers': 0,
                    'incorrect_answers': 0
                }
        else:
            if  exam_id not in exams[examinee_id]:
                exams[examinee_id][exam_id] = {
                    'examinee_name':examinee.name,
                    'exam_title': exam.title,
                    'total_questions': 0,
                    'correct_answers': 0,
                    'incorrect_answers': 0
                }
        exams[examinee_id][exam_id]['total_questions'] += 1
        if response.is_correct():
            exams[examinee_id][exam_id]['correct_answers'] += 1
        else:
            exams[examinee_id][exam_id]['incorrect_answers'] += 1
    
    context = {
        'page_name':"exam_history",
        'exams':exams,
        'page_title':"Exam History"
        
        
    }
    return render(request, "backend/exam-history.html", context)

@login_required(login_url="login/")
def results(request):
    if request.method == "GET":
        exam_id =  request.GET.get('exam_id')
        examinee_id = request.GET.get('examinee_id')
        
        examinee = get_object_or_404(Examinee, id=examinee_id)
        exam = get_object_or_404(Exam, id=exam_id)
        
        if exam.is_time_up() is True:
            messages.success(request, f"Wait for the exam to end: {exam.end_time}")
            return redirect("content:result_submission", exam_id=exam_id)
        responses = ExamineeResponse.objects.filter(examinee=examinee, question__exam=exam).select_related('question', 'selected_choice')

        correct_count = responses.filter(selected_choice__is_correct=True).count()
        incorrect_count = responses.filter(selected_choice__is_correct=False).count()

        # Prepare a list of response details including the correct answer
        response_details = []
        for response in responses:
            correct_choice = response.question.choices.filter(is_correct=True).first()
            response_details.append({
                'question': response.question.text,
                'your_answer': response.selected_choice.text,
                'is_correct': response.selected_choice.is_correct,
                'correct_answer': correct_choice.text if correct_choice else "No correct answer"
            })

        context = {
            'exam': exam,
            'response_details': response_details,
            'correct_count': correct_count,
            'incorrect_count': incorrect_count,
            'examinee':examinee,
            'page_title': 'Exam Results'
        }
    return render(request, "backend/result-details.html", context)

@login_required(login_url="login/")
def examinee_list(request):

templates/backend/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>
    {% block title %}
    Page Title
    {% endblock title %}
    </title>
    <link rel="icon" type="image/x-icon" href="{% static '/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/backend.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'bangla.ttf' %}">
    {% block stylesheet %}
        
    {% endblock stylesheet %}
        
</head>
<body>
    {% include 'backend/side-bar.html' %}
    {% block contents %}
        
    {% endblock contents %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    {% block scripts %}
        
    {% endblock scripts %}
</body>
</html>

templates/backend/exam-add.html
{% extends 'backend/base.html' %} 
{% block title %} {{page_title}} {% endblock title %}


    
{% block contents %}
<div class="container">
    <h1 class="text-center">Exam Add</h1>
    {% for message in messages %}

        {% if message.tags == 'error' %}
            <div class="alert-danger">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
                <strong>{{message}}</strong>
            </div>
        {% elif message.tags == 'success' %}
            <div class="alert-success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
                <strong>{{message}}</strong>
            </div>
        {% endif %}
    {% endfor %}
  <div class="col-md-12 m-4 border rounded p-5">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-4 form-group mb-2">
          <label for="name" class="placeholder">Title*</label>
          {{ form.title }}
        </div>
        <div class="col-md-4 form-group  mb-2">
          <label for="email" class="placeholder">Description*</label>
          {{ form.description }}
        </div>
        <div class="col-md-4 form-group mb-2">
          <label for="father_name" class="placeholder">Start date</label>
          {{ form.start_date }}
        </div>
        <div class="col-md-4 form-group mb-2">
          <label for="education_qualification" class="placeholder">Start time</label>
          {{ form.start_time }}
        </div>
        <div class="col-md-4 form-group mb-2">
          <label for="phone" class="placeholder">End date*</label>
          {{ form.end_date }}
        </div>
        <div class="col-md-4 form-group mb-2">
          <label for="image" class="placeholder">End time</label>
          {{ form.end_time }}
        </div>
        <div class="col-md-12 text-center mt-2">
          <button type="submit" class="btn btn-success ">সেভ</button>
        </div>

      </div>
    </form>
  </div>

</div>
{% endblock contents %}

templates/backend/exam-history.html
{% extends 'backend/base.html' %}
{% block title %} {{page_title}} {% endblock title %}

{% block contents %}
<div class="container p-5">
    <h1 class='text-center'>Exam History</h1>
    
    <table class='table table-striped' >
        <tr>
          <th>Examinee Name</th>
          <th>Exam Name</th>
          <th>Total Questions</th>
          <th>Correct Answers</th>
          <th>Incorrect Answers</th>
          <th>Action</th>
        </tr>

      
    
          
        {% for examinee, stats in exams.items %}
          {% for exam, stat in stats.items %}
            <tr>
                <td> {{stat.examinee_name}} </td>
                <td> {{stat.exam_title}} </td>
                <td> {{stat.total_questions }} </td>
                <td> {{stat.correct_answers }} </td>
                <td> {{stat.incorrect_answers }} </td>
                <td>
                  <form method="get" action="{% url 'backend:results' %}">
                    <input type="hidden" id="exam_id" name="exam_id" value="{{exam}}">
                    <input type="hidden" id="examinee_id" name="examinee_id" value="{{examinee}}">
                    <button type=submit class='btn btn-secondary'>Details</button>
                  </form>

                </td>
              </tr>
          {% endfor %}
        {% endfor %}
            

      </table>
        

</div>
{% endblock contents %}

templates/backend/exam-list.html
{% extends 'backend/base.html' %}
{% block title %} {{page_title}} {% endblock title %}

{% block contents %}
<div class="container">
    <h1 class = 'text-center'>Exam List</h1>
    {% for message in messages %}
    {% if message.tags == 'error' %}
        <div class="error">
            <h2> {{message}}</h2>   
        </div>
    {% elif message.tags == 'success' %}
        <div class="success">
            <h2> {{message}}</h2>
        </div>
    {% endif %}
{% endfor %}
    
<table class='table table-striped' >
    <tr>
      <th style="width:10%;" >SL</th>
      <th style="width:15%;" >Exam Name</th>
      <th style="width:15%;" >Start Date & Time</th>
      <th style="width:15%;" >End Date & Time</th>
      <th style="width:10%;" >Action</th>
    </tr>

    
    {% for single_exam in exams %}
    <tr>
        <td> {{forloop.counter}} </td>
        <td> {{single_exam.title}} </td>
        <td> {{ single_exam.start_time }} </td>
        <td> {{ single_exam.end_time }} </td>
        <td>
          <a href="{% url 'backend:exam_edit' exam_id=single_exam.id %}" class='btn btn-success'><i class="fa-solid fa-pen-to-square"></i></a>
          <a href="{% url 'backend:question' id=single_exam.id %}" class='btn btn-primary'><i class="fa-solid fa-eye"></i></a>
          
          <a href="#" class='btn btn-warning'><i class="fa-solid fa-trash"></i></a>
        </td>
      </tr>
    {% endfor %}
        

  </table>
    

</div>
{% endblock contents %}

templates/backend/examinee-list.html
{% extends 'backend/base.html' %}
{% block title %} {{page_title}} {% endblock title %}

{% block contents %}
<div class="container p-5">
    <h1 class = 'text-center'>Examinee List</h1>
    {% for message in messages %}
    {% if message.tags == 'error' %}
        <div class="error">
            <h2> {{message}}</h2>   
        </div>
    {% elif message.tags == 'success' %}
        <div class="success">
            <h2> {{message}}</h2>
        </div>
    {% endif %}
{% endfor %}
    
<table class='table table-striped' >
    <tr>
      <th style="width:10%;" >SL</th>
      <th style="width:15%;" >Photo</th>
      <th style="width:20%;" >Name</th>
      <th style="width:20%;" >Email</th>
      <th style="width:20%;" >Phone</th>
      <th style="width:15%;" >Action</th>
    </tr>

    
    {% for single_examinee in examinees %}
    <tr>
        <td> {{forloop.counter}} </td>
        <td> 
          <img src="{{single_examinee.image.url}} " style="width:40px;" >
        </td>
        <td> {{single_examinee.name}} </td>
        <td> {{ single_examinee.email }} </td>
        <td> {{ single_examinee.phone }} </td>
        <td>
          <a href="{% url 'backend:examinee_profile_update' id=single_examinee.id %}" class='btn btn-success'><i class="fa-solid fa-pen-to-square"></i></a>
          <a href="{% url 'backend:examinee_profile_page' id=single_examinee.id %}" class='btn btn-primary'><i class="fa-solid fa-eye"></i></a>
          <a href="#" class='btn btn-warning'><i class="fa-solid fa-trash"></i></a>
        </td>
      </tr>
    {% endfor %}
        

  </table>
    

</div>
{% endblock contents %}

templates/backend/examinee-profile-update.html
{% extends 'backend/base.html' %} 
{% block title %} {{page_title}} {% endblock title %}

{% block stylesheet %}

{% endblock stylesheet %}

    
{% block contents %}
<div class="container p-5">
    <h1 class="text-center">Examinee Profile Update</h1>
    {% for message in messages %}

        {% if message.tags == 'error' %}
            <div class="alert-danger">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
                <strong>{{message}}</strong>
            </div>
        {% elif message.tags == 'success' %}
            <div class="alert-success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
                <strong>{{message}}</strong>
            </div>
        {% endif %}
    {% endfor %}
    <div class="col-md-12 m-4 border rounded p-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">Name*</label>
                    {{ form.name }}
                </div>
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">Email*</label>
                    {{ form.email }}
                </div>
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">Father Name</label>
                    {{ form.father_name }}
                </div>
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">Education Qualification</label>
                    {{ form.education_qualification }}
                </div>
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">Mobile*</label>
                    {{ form.phone }}
                </div>
                <div class="col-md-4 form-group mb-2">
                    <label for="name" class="form-label">Picture*</label>
                    {{ form.image }}
                </div>
            </div>
            <div class="col-md-12 text-center mt-2">
                <button type="submit" class="btn btn-success ">Profile Update</button>
              </div>
           
        </form>
    </div>

</div>

{% endblock contents %}

templates/backend/examinee-profile.html
{% extends 'backend/base.html' %} 
{% block title %} {{page_title}} {% endblock title %}
{% block contents %}
<div class="container">
  <div class="col-md-12 m-3">
    <div class="row border p-4">
      <div class="col-md-4 text-end pe-3">
        <img class="profile-img" src=" {{examinee.image.url}} " alt="Profile Picture">
      </div>
      <div class="col-md-8 ps-3 border-left">
        <h1>{{ examinee.name }}</h1>
        <h1>Total Attended Exam: {{ attended_exams_count }} 
          <form method="get" action="{% url 'backend:exam_history' %}">
          <input type="hidden" id="examinee_id" name="examinee_id" value="{{ examinee.id }}">
          <button type="submit" class="badge bg-success">View</button>
        </form>
        </h1> 

        <p class="fs-5"> <strong>Email: </strong>{{ examinee.email }}</p>
        <p class="fs-5"> <strong>Mobile: </strong>{{ examinee.phone }}</p>
        <p class="fs-5"><strong>Father Name:</strong> {{ examinee.father_name }}</p>
        <p class="fs-5"><strong>Education :</strong> {{ examinee.education_qualification }}</p>
      </div>
    </div>
  </div>

</div>

{% endblock contents %}

templates/backend/side-bar.html
<nav class="navbar navbar-expand-lg navbar-custom">
  <div class="container-fluid">
    <span class="navbar-brand fw-bolder fs-4 website-title">Online Exam</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link {% if page_name == 'dashboard' %} active {% endif %}" aria-current="page" href="{% url 'backend:dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if page_name == 'exam_add' %}active{% endif %}" href="{% url 'backend:exam_add' %}">Exam Add</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if page_name == 'exam_list' %}active{% endif %}" href="{% url 'backend:exam_list'%}">Exam List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if page_name == 'question_add' %}active{% endif %}" href="{% url 'backend:question_add'%}">Question Add</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if page_name == 'exam_history' %}active{% endif %}" href="{% url 'backend:exam_history'%}">Exam History</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if page_name == 'exam_list' %}active{% endif %}" href="{% url 'backend:examinee_list'%}">Examinee List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if page_name == 'notification' %}active{% endif %}" href="{% url 'backend:notification'%}">Notification</a>
          </li>


        </ul>
      <div class="d-flex">
        <div class="dropdown">
          <button class="btn btn-success dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		        Admin
            
          </button>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><hr class="dropdown-divider"></li>
            <li><a class="btn btn-primary dropdown-item" href="{% url 'backend:logout' %}">Logout</a></li>
          </ul>
        </div>

          
      </div>
    </div>
  </div>
</nav>