contents/urls.py
from django.urls import path
from . import views
app_name = "content"
urlpatterns = [
    path('',views.dashboard, name="dashboard"),
    path('profile/',views.profile_page, name='profile'),
    
    path('exams/',views.exam_cat, name="exam"),
    path('exams/<int:id>/',views.question, name="question"),
    path('exam-history/',views.exam_history, name="exam_history"),
    path('results/<int:exam_id>/',views.results, name="results"),
    path('results-submission/<int:exam_id>/',views.result_submission, name="result_submission"),
    
    path('message/<int:exam_id>/',views.messages_page, name="message"),
    path('profile-update  /',views.profile_update, name="profile_update"),
    path('logout/',views.logout, name="logout"),
    
    path("notification/",views.NotificationListView.as_view(),name="notification" ),
    path("notification/<int:pk>/",views.NotificationDetailView.as_view(),name="notification_details" )
    
    
    
    
    
]

onlineExam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('contents.urls')),
    path('backend/', include('backend.urls')),
    
    
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register, login, otp_verify
app_name = "user"
urlpatterns = [
    path("register/",register,name="register"),
    path("login/",login,name="login"),
    path("otp/",otp_verify,name="otp"),
    
    
]

templates/includes/side-bar.html
<nav class="navbar navbar-expand-lg navbar-custom">
  <div class="container-fluid">
    <a class="navbar-brand fs-2 title" href="#">অনলাইন পরীক্ষা</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {% if is_logged_in %}

          <li class="nav-item">
            <a class="nav-link fs-5 {% if page_name == 'dashboard' %} active {% endif %}" aria-current="page" href="{% url 'content:dashboard' %}">হোম</a>
          </li>
          <li class="nav-item">
            <a class="nav-link fs-5 {% if page_name == 'exam' %}active{% endif %}" href="{% url 'content:exam' %}">পরীক্ষায় অংশগ্রহণ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link fs-5 {% if page_name == 'exam_history' %}active{% endif %}" href="{% url 'content:exam_history'%}">রেজাল্ট সমূহ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link fs-5 {% if page_name == 'notification' %}active{% endif %}" href="{% url 'content:notification'%}">নোটিফিকশন </a>
          </li>

      {% endif %}

        </ul>
      <div class="d-flex">
        
        {% if is_logged_in %}
        <ul class="notification-drop">
          <li class="item">
            <i class="fa-solid fa-bell"></i>
            {% if unread_notifications > 0 %}
            <span class="btn__badge pulse-button">{{unread_notifications}}</span>     
            {% endif %}
              <ul>
                {% for notification in notifications %}
                <li class="position-relative">
                  <a href="{% url 'content:notification_details' pk=notification.id %}" class='link'>
                    {{ notification.message }}
                </a>
                  {% if notification.is_read == False %} 
                  <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
                    
                  </span>
                  {% endif %} 
                </li>
                <hr>
                {% endfor %}
              </ul>
          </li>
      </ul>
        <div class="dropdown">
          <button class="btn btn-success dropdown-toggle fs-5" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		        <img class="rounded-circle" style="width:40px; height:40px;" src="{{ examinee.image.url }}" />
            
            {{examinee.name}} 
          </button>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="btn btn-primary dropdown-item fs-5" href="{% url 'content:profile' %}">প্রোফাইল</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="btn btn-primary dropdown-item fs-5" href="{% url 'content:logout' %}">লগআউট</a></li>
          </ul>
        </div>
        {% else %}
          <a class="btn btn-primary" href="#">লগইন</a>
        {% endif %}
          
      </div>
    </div>
  </div>
</nav>