contents/urls.py
from django.urls import path
from . import views
app_name = "content"
urlpatterns = [
    path('',views.dashboard, name="dashboard"),
    path('profile/',views.profile_page, name='profile'),
    
    path('exams/',views.exam_cat, name="exam"),
    path('exams/<int:id>/',views.question, name="question"),
    path('exam-history/',views.exam_history, name="exam_history"),
    path('results/<int:exam_id>/',views.results, name="results"),
    path('results-submission/<int:exam_id>/',views.result_submission, name="result_submission"),
    
    path('message/<int:exam_id>/',views.messages_page, name="message"),
    path('profile-update  /',views.profile_update, name="profile_update"),
    path('logout/',views.logout, name="logout"),
    
    path("notification/",views.NotificationListView.as_view(),name="notification" ),
    path("notification/<int:pk>/",views.NotificationDetailView.as_view(),name="notification_details" )
    
    
    
    
    
]

onlineExam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('contents.urls')),
    path('backend/', include('backend.urls')),
    
    
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register, login, otp_verify
app_name = "user"
urlpatterns = [
    path("register/",register,name="register"),
    path("login/",login,name="login"),
    path("otp/",otp_verify,name="otp"),
    
    
]

contents/models.py
from django.db import models
from users.models import Examinee
from django.utils import timezone


class Exam(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def is_time_up(self):
        if self.end_time > timezone.now():
            return True
        else:
            return False
        
    def is_start_time(self):
        if self.start_time < timezone.now():
            return True
        else:
            return False

class Question(models.Model):
    exam = models.ForeignKey(Exam, related_name='questions', on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

class ExamineeResponse(models.Model):
    examinee = models.ForeignKey(Examinee, related_name='responses', on_delete=models.CASCADE)
    question = models.ForeignKey(Question, related_name='responses', on_delete=models.CASCADE)
    selected_choice = models.ForeignKey(Choice, related_name='responses', on_delete=models.CASCADE)
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.examinee} - {self.question.text} - {self.selected_choice.text}'
    
    def is_correct(self):
        return self.selected_choice.is_correct
    
    
class Notification(models.Model):
    is_read = models.BooleanField(default=False)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    examinee = models.ForeignKey(Examinee, on_delete=models.CASCADE, null=True, blank=True)
    

contents/forms.py
from django import forms
from .models import Examinee

class ExamineeUpdateForm(forms.ModelForm):
    class Meta:
        model = Examinee
        fields = ['name', 'email', 'father_name', 'education_qualification', 'phone', 'image']

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'id':"name", 'placeholder': ''}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'id':"email",'placeholder': ''}),
            'father_name': forms.TextInput(attrs={'class':'form-control', 'id':"father_name",'placeholder': ''}),
            'education_qualification': forms.TextInput(attrs={'class':'form-control','id':"education_qualification", 'placeholder': ''}),
            'phone': forms.TextInput(attrs={'class':'form-control', 'id':'phone', 'placeholder': ''}),
            'image': forms.ClearableFileInput(attrs={'class':'form-control-file', 'id':"image", 'placeholder': 'Upload Profile Picture'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['father_name'].required = False
        self.fields['education_qualification'].required = False
        self.fields['image'].required = False

contents/views.py
import json
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.db.models import Count
from users.models import Examinee
from .models import Exam, Question, Choice, ExamineeResponse, Notification
from django.contrib import messages
from django.http import JsonResponse
from .forms import ExamineeUpdateForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from . import email_sender

def dashboard(request):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")

    context = {
        'page_name':"dashboard",
        'page_title':"ড্যাশর্বোড",
        'is_logged_in': True,
        }
    return render(request,"contents/dashboard.html", context)

    
def profile_page(request):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")
    context = {
        'page_title':"প্রোফাইল",
        'is_logged_in': True
        }
    return render(request,"contents/profile.html", context)
def exam_cat(request):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")
    exams = Exam.objects.all()
    context =  {
        'exams':exams, 
        'page_name':"exam",
        'page_title':"পরীক্ষা সমূহ",
        'is_logged_in': True
        }
    return render(request,"contents/exam-cat.html",context)
    
def messages_page(request,exam_id):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")
    exam = Exam.objects.filter(id=exam_id).first()
    if exam is None:
        return redirect("content:exam")
    if not exam.is_time_up():
            messages.error(request, "সময় শেষ")
    if not exam.is_start_time():
            messages.warning(request, "পরীক্ষা শুরু হয় নাই")
            
    context = {
        "exam":exam,  
        'is_logged_in': True,
        'page_title' : "বার্তা"
               }
    return render(request, "contents/message.html",context)

def question(request, id):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")
    
    exam = Exam.objects.filter(id=id).first()
    
    if exam.is_time_up() is False:
        return redirect("content:message", exam_id=id)
    if exam.is_start_time()  is False:
        return redirect("content:message", exam_id=id)
    
    
    examinee = Examinee.objects.filter(email=request.session.get('user_email')).first()
    
    examineeResponse = ExamineeResponse.objects.filter(examinee=examinee,question__exam=exam).first()
    # print(examineeResponse)
    
    if examineeResponse:
        messages.success(request, "আপনি ইতি মধ্যে পরীক্ষায় অংশগ্রহণ করছেন")
        return redirect('content:result_submission', exam_id=id)
    
    if request.method == 'POST':
        if exam.is_time_up() is False:
            messages.error(request, f"সময় শেষ হবে: {exam.end_time}")
            return redirect("content:result_submission", exam_id=id)
        # Process the form submission
        for question in Question.objects.filter(exam=exam):
            choice_id = request.POST.get(f'question_{question.id}')
            if choice_id:
                selected_choice = get_object_or_404(Choice, id=choice_id)
                ExamineeResponse.objects.create(
                    examinee=examinee,
                    question=question,
                    selected_choice=selected_choice
                )
        messages.success(request, "আপনার পরীক্ষা সাবমিট হয়েছে!")
        return redirect("content:result_submission", exam_id=id)
    
    if exam is not None:
        questions = Question.objects.filter(exam=exam)
        questions_with_choices = []
        
        for question in questions:
            choices = Choice.objects.filter(question=question)
            questions_with_choices.append({
                'question' : question,
                'choices' : choices
            })
        context = {
            'questions_with_choices':questions_with_choices, 
            'examinee':examinee, 
            "exam":exam,
            'page_name':"exam",
            'page_title':"প্রশ্ন",
            'is_logged_in': True

            
            }
        return render(request,"contents/question.html",context)
    else:
        return redirect("content:exam")
    

def results(request, exam_id):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")
    
    examinee = get_object_or_404(Examinee, email=request.session.get('user_email'))
    exam = get_object_or_404(Exam, id=exam_id)
    
    if exam.is_time_up() is True:
        messages.success(request, f"পরীক্ষা শেষ হওয়া পর্যন্ত অপেক্ষা করুন: {exam.end_time}")
        return redirect("content:result_submission", exam_id=exam_id)
    responses = ExamineeResponse.objects.filter(examinee=examinee, question__exam=exam).select_related('question', 'selected_choice')

    correct_count = responses.filter(selected_choice__is_correct=True).count()
    incorrect_count = responses.filter(selected_choice__is_correct=False).count()

    # Prepare a list of response details including the correct answer
    response_details = []
    for response in responses:
        correct_choice = response.question.choices.filter(is_correct=True).first()
        response_details.append({
            'question': response.question.text,
            'your_answer': response.selected_choice.text,
            'is_correct': response.selected_choice.is_correct,
            'correct_answer': correct_choice.text if correct_choice else "No correct answer"
        })

    context = {
        'exam': exam,
        'response_details': response_details,
        'correct_count': correct_count,
        'incorrect_count': incorrect_count,
        'page_title': 'পরীক্ষার ফলাফল',
                    'is_logged_in': True

    }
    return render(request, "contents/result-details.html", context)

def exam_history(request):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")
    
    examinee = Examinee.objects.filter(email=request.session.get('user_email')).first()
    responses = ExamineeResponse.objects.filter(examinee=examinee).select_related('question__exam', 'selected_choice')
    
    # print(responses)
    # Group by exam and calculate the correct/incorrect counts
    exams = {}
    for response in responses:
        exam = response.question.exam
        exam_id = exam.id
        if exam_id not in exams:
            exams[exam_id] = {
                'exam_title': exam.title,
                'total_questions': 0,
                'correct_answers': 0,
                'incorrect_answers': 0
            }
        exams[exam_id]['total_questions'] += 1
        if response.is_correct():
            exams[exam_id]['correct_answers'] += 1
        else:
            exams[exam_id]['incorrect_answers'] += 1
    # import json module

    # return JsonResponse(exams)
    
    context = {
        'page_name':"exam_history",
        'exams':exams,
        'page_title':"পরীক্ষার  ইতিহাস",
                    'is_logged_in': True

        
        
    }
    return render(request, "contents/exam-history.html", context)

def result_submission(request, exam_id):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")
    

    context = {
        'page_name':"exam_history",
        'page_title':"পরীক্ষা জমা",
        'exam_id':exam_id,
        'is_logged_in': True

        
    }
    return render(request, "contents/result-submission.html", context)

def logout(request):
    request.session.flush()
    return redirect('user:login')


def profile_update(request):
    if not request.session.get('is_logged_in'):
        return redirect("user:login")
    examinee = Examinee.objects.filter(email=request.session.get('user_email')).first()
    if request.method == 'POST':
        form = ExamineeUpdateForm(request.POST, request.FILES, instance=examinee)
        if form.is_valid():
            email = form.cleaned_data['email']
            form.save()
            request.session['is_logged_in'] = True
            request.session['user_email'] = email
            messages.success(request, "প্রোফাইল সফল ভাবে আপডেট হয়েছে")
            return redirect("content:profile_update")  # Redirect to a profile page or other relevant page
        else:
            messages.error(request, "কোনো সমস্যা হয়েছে")
    else:
        form = ExamineeUpdateForm(instance=examinee)  # Pre-populate form with existing data

    return render(request, "contents/profile-update.html", {'form': form, 'examinee':examinee,  'is_logged_in': True})


class NotificationListView(ListView):
    model = Notification
    context_object_name = 'notifications'
    template_name = 'contents/notification_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.session.get('is_logged_in'):
            return redirect("user:login")
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # Fetch examinee based on session email
        self.examinee = Examinee.objects.filter(email=self.request.session.get('user_email')).first()
        return Notification.objects.filter(examinee=self.examinee).order_by("-timestamp")

    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        context['page_title'] = "নোটিফিকশন"
        context['page_name'] = "notification"
        context['is_logged_in'] = True
        return context


class NotificationDetailView(DetailView):
    
    model = Notification
    context_object_name = 'notification'
    template_name = 'contents/notification-details.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not request.session.get('is_logged_in'):
            return redirect("user:login")
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        notification = self.get_object()

templates/contents/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>
    {% block title %}
    Page Title
    {% endblock title %}
    </title>
    <link rel="icon" type="image/x-icon" href="{% static '/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/contents.css' %}">
    {% block stylesheet %}
        
    {% endblock stylesheet %}
        
</head>
<body>
    {% include 'includes/side-bar.html' %}
    {% block contents %}
        
    {% endblock contents %}
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    
    {% block scripts %}
        
    {% endblock scripts %}
        
        


</body>
</html>

templates/contents/dashboard.html
{% extends 'users/base.html' %} 
{% block title %} {{page_title}} {% endblock title %}
{% block contents %}
<div class="container">
  <h1 class="text-center mt-5">অনলাইন পরীক্ষায় আপনাকে স্বাগতম</h1>
</div>
{% endblock contents %}

templates/contents/exam-cat.html
{% extends 'users/base.html' %} 
{% block title %} {{page_title}} {% endblock title %}
{% block contents %}
<main>

  <div class="content">
    <div class="d-flex justify-content-center mx-auto">
        
        
        {% for single_exam in exams %}
        <div class="card m-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{single_exam.title}}</h5>
            <p class="card-text">{{single_exam.description|slice:40}}</p>
            <p class="card-text">শুরুর সময়: {{single_exam.start_time}}</p>
            <p class="card-text">শেষের সময়: {{single_exam.end_time}}</p>

            <a href="{% url 'content:question' id=single_exam.id %}" class="btn btn-primary"> পরীক্ষায় অংশগ্রহণ</a>
          </div>
        </div>
        {% endfor %}
            
        
    </div>
  </div>
</main>
{% endblock contents %}

templates/contents/exam-history.html
{% extends 'users/base.html' %}
{% block title %} {{page_title}} {% endblock title %}

{% block contents %}
<div class="container p-5">
    <h1 class="text-center">পরীক্ষা সমূহ</h1>
<table class='table table-hover border' >
    <tr>
      <th>পরীক্ষা নাম</th>
      <th>মোট প্রশ্ন</th>
      <th>সঠিক উত্তর</th>
      <th>ভুল উত্তর</th>
      <th>ক্রিয়া</th>
    </tr>

    
    {% for exam, stats in exams.items %}
    <tr>
        <td> {{stats.exam_title}} </td>
        <td> {{ stats.total_questions }} </td>
        <td> {{ stats.correct_answers }} </td>
        <td> {{ stats.incorrect_answers }} </td>
        <td><a href="{% url 'content:results' exam_id=exam %}" class='btn btn-primary'>বিস্তারিত</a></td>
      </tr>
    {% endfor %}
        

  </table>
    

</div>
{% endblock contents %}

templates/contents/message.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %} {{page_title}} {% endblock title %}


{% block stylesheet %}

{% endblock stylesheet %}
    
{% block contents %}
<div class="content">
    <div class="d-flex justify-content-center mx-auto">
        <div class="card m-3" style="width: auto;">
            {% for message in messages %}
            {% if message.tags == 'error' %}
            <div class="card-body">
                <img class="card-img-top" src="{% static 'images\timesup.gif' %}" alt="Girl in a jacket" style="width:200px !important;">
    
                  <h2 class="card-title text-center">{{message}}</h2>
                </div>

            {% elif message.tags == 'warning' %}
            <div class="card-body">
    
                  <h2 class="card-title">{{exam.title}}</h2>
                  <p class="card-text">পরীক্ষা শুরু হবে: {{exam.start_time}}</p>
                  <p class="card-text text-center">সময় অবশিষ্ট আছে </p>
                  <div id="timer" class='timer d-flex'>
                    <div class="fs-4 p-2" id="days"></div>  
                    <div class="fs-4 p-2" id="hours"></div>
                    <div class="fs-4 p-2" id="minutes"></div>
                    <div class="fs-4 p-2" id="seconds"></div>
                </div>
                <div class="col-md-12 text-center mt-2">
                    <a id="start_exam" class='btn btn-success' style="display:none" href="{% url 'content:question' id=exam.id %}">পরীক্ষা শুরু</a>

                  </div>

                </div>

            {% endif %}
        {% endfor %}

          </div>
    </div>
</div>


</div>
{% endblock contents %}

{% block scripts %}
<script>
    function makeTimer() {
        // Replace this line with the correctly formatted time string or timestamp
        var endTime = new Date("{{ exam.start_time|date:'F d, Y H:i:s' }}").getTime(); 
        
        var now = new Date().getTime();
        var timeLeft = endTime - now;
        var days = Math.floor(timeLeft / (1000 * 60 * 60 * 24));
        var hours = Math.floor((timeLeft % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((timeLeft % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((timeLeft % (1000 * 60)) / 1000);

        if (days > 0) {
            document.getElementById("days").innerHTML = days + "<span>Days</span>";
        }
        if ( days < 0 && hours < 0 && minutes < 0 && seconds < 0 ){
            document.getElementById("start_exam").style.display = "inline";
            document.getElementById("timer").style.display = "none";

        }else{
            document.getElementById("start_exam").style.display = "none";
        }
        
        document.getElementById("hours").innerHTML = hours + "<span>Hours</span>";
        document.getElementById("minutes").innerHTML = minutes + "<span>Minutes</span>";
        document.getElementById("seconds").innerHTML = seconds + "<span>Seconds</span>";
        
        // Stop the timer when the countdown is over
        if (timeLeft < 0) {
            clearInterval(timerInterval);
            document.getElementById("timer").innerHTML = "EXPIRED";
        }
    }

    var timerInterval = setInterval(makeTimer, 1000);
</script>

{% endblock scripts %}
    

templates/contents/notification-details.html
{% extends 'users/base.html' %}
{% block title %} {{page_title}} {% endblock title %}

{% block contents %}
<div class="container p-5">
    <h1 class="text-center">নোটিফিকশন </h1>
    
    <p> {{notification.message}} </p>
    
        
</div>
{% endblock contents %}

templates/contents/notification_list.html
{% extends 'users/base.html' %}
{% block title %} {{page_title}} {% endblock title %}

{% block contents %}
<div class="container p-5">
    <h1 class="text-center">নোটিফিকশন </h1>
    
    {% for notification in notifications %}
    <li class="position-relative" >
        <a href="{% url 'content:notification_details' pk=notification.id %}" class='btn'>
            {{ notification.message }}
        </a>
        {% if notification.is_read == False %} 
            <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle"></span>
        {% endif %} 
    </li>
    <hr>         
    {% endfor %}
    
        
</div>
{% endblock contents %}

templates/contents/profile-update.html
{% extends 'users/base.html' %} 
{% block title %} {{page_title}} {% endblock title %}

{% block stylesheet %}

{% endblock stylesheet %}

    
{% block contents %}
<div class="container">
    <h1 class="text-center">প্রোফাইল আপডেট</h1>
    {% for message in messages %}

        {% if message.tags == 'error' %}
            <div class="alert-danger">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
                <strong>{{message}}</strong>
            </div>
        {% elif message.tags == 'success' %}
            <div class="alert-success">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
                <strong>{{message}}</strong>
            </div>
        {% endif %}
    {% endfor %}
    <div class="col-md-12 m-4 border rounded p-5">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">নাম*</label>
                    {{ form.name }}
                </div>
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">ইমেইল*</label>
                    {{ form.email }}
                </div>
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">পিতার নাম</label>
                    {{ form.father_name }}
                </div>
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">শিক্ষাগত যোগ্যতা</label>
                    {{ form.education_qualification }}
                </div>
                <div class="col-md-4 form-group mb-2 fs-3">
                    <label for="name" class="form-label">মোবাইল*</label>
                    {{ form.phone }}
                </div>
                <div class="col-md-4 form-group mb-2">
                    <label for="name" class="form-label">ছবি*</label>
                    {{ form.image }}
                </div>
            </div>
            <div class="col-md-12 text-center mt-2">
                <button type="submit" class="btn btn-success ">আপডেট প্রোফাইল</button>
              </div>
           
        </form>
    </div>

</div>

{% endblock contents %}

templates/contents/profile.html
{% extends 'users/base.html' %} 
{% block title %} {{page_title}} {% endblock title %}
{% block contents %}
<div class="container">
  <div class="col-md-12 m-3">
    <div class="row border p-4">
      <div class="col-md-4 text-end pe-3">
        <img class="profile-img" src=" {{examinee.image.url}} " alt="Profile Picture">
      </div>
      <div class="col-md-8 ps-3 border-left">
        <h1>{{ examinee.name }}</h1>
        <p class="fs-5"> <strong>ইমেইল: </strong>{{ examinee.email }}</p>
        <p class="fs-5"> <strong>মোবাইল: </strong>{{ examinee.phone }}</p>
        <p class="fs-5"><strong>পিতার নাম:</strong> {{ examinee.father_name }}</p>
        <p class="fs-5"><strong>শিক্ষাগত যোগ্যতা:</strong> {{ examinee.education_qualification }}</p>
        <a class='btn btn-primary' href="{% url 'content:profile_update' %}"><i class="fa-solid fa-pen-to-square"></i> আপডেট</a>

      </div>
    </div>
  </div>

</div>

{% endblock contents %}

templates/contents/question.html
{% extends 'users/base.html' %} 
{% block title %} {{page_title}} {% endblock title %}

{% block stylesheet %}
<style>
    #days {
        font-size: 30px;
        color: #db4844;
      }
      #hours {
        font-size: 30px;
        color: #f07c22;
      }
      #minutes {
        font-size: 30px;
        color: #f6da74;
      }
      #seconds {
        font-size: 30px;
        color: #abcd58;
      }
      span {
        display: block;
        font-size: 20px;
      }
      
      .timer {
        text-align: center;
        color: white;
        background: #222;
        position:fixed;
      }
</style>
    
{% endblock stylesheet %}
    

{% block contents %}
<div id="timer" class ="timer">
  <div id="days"></div>
  <div id="hours"></div>
  <div id="minutes"></div>
  <div id="seconds"></div>
</div>

<div class="container">
    <div class="border m-5 ">
        <h1 class="text-center"> {{exam.title}} </h1>
        <form id="quiz-form" method='post' class="card p-5">
            {% csrf_token %}
            {% for question in questions_with_choices %}
                <div class="question">
                    <h3> {{forloop.counter}}. {{question.question.text}} </h3>
                    <ol class="c">
                    {% for choice in question.choices %}
                        <li><label><input type="radio" name="question_{{question.question.id}}" value="{{ choice.id }}"> {{choice.text}} </label></li>
                    {% endfor %}
                </ol>

                </div>
            {% endfor %}
                
            <div class="col-md-12 text-center mt-2">
              <button type="submit" id="submit" class="btn btn-success" >জমা দিন</button>
            </div>
        </form>
        <div id="result"></div>
    </div>
  </div>


{% endblock contents %}

{% block scripts %}
<script>
    function makeTimer() {
        // Replace this line with the correctly formatted time string or timestamp
        var endTime = new Date("{{ exam.end_time|date:'F d, Y H:i:s' }}").getTime(); 
        //var endTime = new Date("August 26, 2024 18:00:00 PDT");     
        
        var now = new Date().getTime();
        var timeLeft = endTime - now;
        var days = Math.floor(timeLeft / (1000 * 60 * 60 * 24));
        var hours = Math.floor((timeLeft % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((timeLeft % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((timeLeft % (1000 * 60)) / 1000);
        if (days > 0) {
            document.getElementById("days").innerHTML = days + "<span>Days</span>";
        }
        if (hours > 0) {
            document.getElementById("hours").innerHTML = hours + "<span>Days</span>";
        }
        document.getElementById("minutes").innerHTML = minutes + "<span>Minutes</span>";
        document.getElementById("seconds").innerHTML = seconds + "<span>Seconds</span>";
        
        if ( days < 0 && hours < 0 && minutes < 0 && seconds < 0 ){

            document.getElementById("submit").style.display = "none";

        }else{
        }

        // Stop the timer when the countdown is over
        if (timeLeft < 0) {
            clearInterval(timerInterval);
            document.getElementById("timer").innerHTML = "EXPIRED";
        }
    }

    var timerInterval = setInterval(makeTimer, 1000);
</script>

{% endblock scripts %}

templates/contents/result-details.html
{% extends 'users/base.html' %}
{% block title %} {{ page_title }} {% endblock title %}

{% block contents %}
<div class="container p-5">
    <h1 class='text-center'>{{ exam.title }} এর রেজাল্ট</h1>
    <table class="table table-striped">
        <tr>
            <th class="text-center">মোট প্রশ্ন</th>
            <th class="text-center">সঠিক উত্তর</th>
            <th class="text-center">ভুল উত্তর</th>
        </tr> 
        <tr> 
            <td class="text-center">{{ response_details|length }}</td>
            <td class="text-center">{{ correct_count }}</td>
            <td class="text-center">{{ incorrect_count }}</td>
        </tr>
    </table>
    
    <div class="card p-5">
        {% for detail in response_details %}
        <div class="card-body">
            {{ forloop.counter }}. {{ detail.question }} <br>
            আপনার উত্তর: {{ detail.your_answer }} - 
            {% if detail.is_correct %}
                <span class="badge bg-success">সঠিক</span>
            {% else %}
                <span class="badge bg-danger">ভুল</span> <br>
                <span class="bg-success text-light p-1 mt-2">সঠিক উত্তর: {{ detail.correct_answer }}</span>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    
</div>
{% endblock contents %}

templates/contents/result-submission.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %} {{page_title}} {% endblock title %}

{% block contents %}
<div class="content">
    <div class="d-flex justify-content-center mx-auto">
    
    <div class="card m-3" style="width: auto;">
        {% for message in messages %}
        {% if message.tags == "success" %}
        <div class="card-body mx-auto">
            <div class="img">
            <img class="text-center" style="width:200px;"  src="{% static 'images\checked.png' %}" alt="Girl in a jacket">

            </div>
            <h2> {{message}} </h2>   
            <div class="col-md-12 text-center mt-2">
                <a class='btn btn-success' href="{% url 'content:results' exam_id=exam_id %}">View Results</a> 
              </div>
            </div>
        {% elif message.tags == "error" %}
        <div class="card-body">
            <img class="card-img-top"  src="{% static 'images\cancel.png' %}" alt="Girl in a jacket">
            <h2> {{message}} </h2>   
            </div>
        {% endif %}
            
        
    {% endfor %}
    </div>
    </div>

</div>
{% endblock contents %}